# Generated by Django 4.1.7 on 2023-02-24 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_option_response_question_option_question'),
        ('account', '0004_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.classroom'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'admin')], default=2),
        ),
    ]
