# Generated by Django 4.1.7 on 2023-02-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_student_classroom_alter_account_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Teacheruser',
            new_name='user',
        ),
    ]
