# Generated by Django 4.1.7 on 2023-02-28 04:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_alter_account_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="birth_date",
        ),
    ]
