# Generated by Django 4.1.7 on 2023-02-28 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_remove_account_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="email",
        ),
    ]
