# Generated by Django 4.1.7 on 2023-03-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0011_alter_classroom_teacher_alter_exam_classroom_and_more"),
        ("account", "0010_remove_account_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="classroom",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="academics.classroom",
            ),
        ),
    ]
