# Generated by Django 4.1.7 on 2023-03-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0018_enrollment"),
        ("account", "0012_alter_account_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="classroom",
        ),
        migrations.AddField(
            model_name="student",
            name="classroom",
            field=models.ManyToManyField(
                default=1,
                related_name="students",
                through="academics.Enrollment",
                to="academics.classroom",
            ),
        ),
    ]
