# Generated by Django 4.1.7 on 2023-03-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0020_attendance"),
        ("account", "0013_remove_student_classroom_student_classroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="classroom",
            field=models.ManyToManyField(
                default=None,
                related_name="students",
                through="academics.Enrollment",
                to="academics.classroom",
            ),
        ),
    ]
