# Generated by Django 4.1.7 on 2023-02-24 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_student_classroom_alter_account_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=25)),
                ('class_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='Sports_festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Try_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tryno', models.IntegerField()),
                ('result', models.IntegerField()),
                ('eventreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event_registration')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='fest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.sports_festival'),
        ),
    ]
