# Generated by Django 4.1.7 on 2023-03-28 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default=None, max_length=25)),
                (
                    "event_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "Time"), (1, "Distance")],
                        default=None,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventregistrations",
                        to="event.event",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventregistrations",
                        to="account.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SportsFestival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Try",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.FloatField(blank=True, default=2, null=True)),
                (
                    "event_reg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tries",
                        to="event.eventregistration",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="fest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="event.sportsfestival",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="standards",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="events",
                to="academics.classroom",
            ),
        ),
    ]
