# Generated by Django 4.1.7 on 2023-03-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0011_alter_student_classroom"),
        ("event", "0008_rename_eventreg_try_event_reg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="fest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="event.sportsfestival",
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventregistrations",
                to="event.event",
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventregistrations",
                to="account.student",
            ),
        ),
        migrations.AlterField(
            model_name="try",
            name="event_reg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tries",
                to="event.eventregistration",
            ),
        ),
    ]
