# Generated by Django 4.1.7 on 2023-03-02 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0009_alter_event_fest_alter_eventregistration_event_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="sportsfestival",
            old_name="fest",
            new_name="name",
        ),
    ]
