# Generated by Django 4.1.7 on 2023-03-07 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0010_rename_event_event_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_time",
        ),
    ]
