# Generated by Django 4.1.7 on 2023-03-07 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0012_alter_try_result_alter_try_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="try",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="try",
            name="try_no",
        ),
    ]
