# Generated by Django 4.1.7 on 2023-03-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0019_alter_classroom_unique_together"),
        ("event", "0013_alter_try_unique_together_remove_try_try_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="class_limit",
        ),
        migrations.AddField(
            model_name="event",
            name="standards",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="events",
                to="academics.classroom",
            ),
        ),
    ]
