# Generated by Django 4.1.7 on 2023-03-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0019_alter_classroom_unique_together"),
        ("event", "0014_remove_event_class_limit_event_standards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="standards",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="eventclassrooms",
                to="academics.classroom",
            ),
        ),
    ]
