# Generated by Django 4.1.7 on 2023-03-28 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="account.student",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="academics.exam",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="academics.question",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="academics.classroom",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.classroom"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.student"
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="teacher",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom",
                to="account.teacher",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together={("standard", "division")},
        ),
    ]
