# Generated by Django 4.1.7 on 2023-03-29 09:21

import academics.constants
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="division",
            field=models.IntegerField(
                blank=True,
                default=academics.constants.Divisions["A"],
                verbose_name=(
                    (101, "A"),
                    (102, "B"),
                    (103, "C"),
                    (104, "D"),
                    (105, "E"),
                    (106, "F"),
                    (107, "G"),
                    (108, "H"),
                    (109, "I"),
                    (110, "J"),
                    (111, "K"),
                    (112, "L"),
                    (113, "M"),
                    (114, "N"),
                    (115, "O"),
                    (116, "P"),
                    (117, "Q"),
                    (118, "R"),
                    (119, "S"),
                    (120, "T"),
                    (121, "U"),
                    (122, "V"),
                    (123, "W"),
                    (124, "X"),
                    (125, "Y"),
                    (126, "Z"),
                ),
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="end_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="name",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="exam",
            name="start_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="option",
            name="text",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="response",
            name="option",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="selected_options",
                to="academics.option",
            ),
        ),
    ]
