# Generated by Django 4.1.7 on 2023-02-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_exam_end_time_alter_exam_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='option',
        ),
        migrations.AddField(
            model_name='response',
            name='option',
            field=models.ManyToManyField(blank=True, null=True, related_name='selected_options', to='academics.option'),
        ),
    ]
