# Generated by Django 4.1.7 on 2023-03-30 03:50

import academics.constants
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0008_alter_classroom_division"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="classroom",
            name="academic_year",
            field=models.IntegerField(blank=True, default=2023),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="division",
            field=models.IntegerField(
                blank=True,
                default=academics.constants.Divisions["A"],
                verbose_name=(
                    (101, "A"),
                    (102, "B"),
                    (103, "C"),
                    (104, "D"),
                    (105, "E"),
                    (106, "F"),
                    (107, "G"),
                    (108, "H"),
                    (109, "I"),
                    (110, "J"),
                    (111, "K"),
                    (112, "L"),
                    (113, "M"),
                    (114, "N"),
                    (115, "O"),
                    (116, "P"),
                    (117, "Q"),
                    (118, "R"),
                    (119, "S"),
                    (120, "T"),
                    (121, "U"),
                    (122, "V"),
                    (123, "W"),
                    (124, "X"),
                    (125, "Y"),
                    (126, "Z"),
                ),
            ),
        ),
    ]
