# Generated by Django 4.1.7 on 2023-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0009_remove_response_option_response_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="option",
            field=models.ManyToManyField(
                blank=True, related_name="selected_options", to="academics.option"
            ),
        ),
    ]
