# Generated by Django 4.1.7 on 2023-03-30 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_account_user_type"),
        ("academics", "0010_delete_subject_alter_classroom_division_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together={("teacher", "academic_year")},
        ),
    ]
