# Generated by Django 4.1.7 on 2023-03-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0011_alter_classroom_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(blank=True, default=2020)),
            ],
        ),
        migrations.CreateModel(
            name="ExamStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name="exam",
            name="classroom",
        ),
        migrations.CreateModel(
            name="ExamStandardSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.examstandard",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.subject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="examstandard",
            name="Standard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.standard"
            ),
        ),
        migrations.AddField(
            model_name="examstandard",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.exam"
            ),
        ),
        migrations.AddField(
            model_name="examstandard",
            name="subjects",
            field=models.ManyToManyField(
                through="academics.ExamStandardSubject", to="academics.subject"
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="subjects",
            field=models.ManyToManyField(
                related_name="classroom_subjects", to="academics.subject"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="academics_year",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="standard",
            field=models.ManyToManyField(
                related_name="exam_standards",
                through="academics.ExamStandard",
                to="academics.standard",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="academics.academicyear",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="standard",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="academics.standard",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="academics.examstandardsubject",
            ),
        ),
    ]
