# Generated by Django 4.1.7 on 2023-03-03 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0012_alter_account_user_type"),
        ("academics", "0012_rename_exam_exam_name_rename_option_option_text_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together={("id", "teacher")},
        ),
    ]
