# Generated by Django 4.1.7 on 2023-03-03 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0012_alter_account_user_type"),
        ("academics", "0013_alter_classroom_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom",
                to="account.teacher",
                unique=True,
            ),
        ),
    ]
