# Generated by Django 4.1.7 on 2023-03-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0013_rename_year_academicyear_start_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="end_year",
            field=models.IntegerField(blank=True, default=2020, unique=True),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="start_year",
            field=models.IntegerField(blank=True, default=2020, unique=True),
        ),
        migrations.AlterField(
            model_name="standard",
            name="name",
            field=models.IntegerField(blank=True, default=1, unique=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(blank=True, default="", max_length=25, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="academicyear",
            unique_together={("start_year", "end_year")},
        ),
    ]
