# Generated by Django 4.1.7 on 2023-03-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0015_alter_classroom_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="mark",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
