# Generated by Django 4.1.7 on 2023-03-31 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0015_alter_exam_end_time_alter_exam_start_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="end_time",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="exam",
            old_name="start_time",
            new_name="start_date",
        ),
    ]
