# Generated by Django 4.1.7 on 2023-03-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0016_question_mark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="mark",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
