# Generated by Django 4.1.7 on 2023-03-31 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0017_rename_standard_examstandard_standard"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exam",
            unique_together={("academics_year", "name")},
        ),
    ]
