# Generated by Django 4.1.7 on 2023-03-06 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0018_enrollment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together={("standard", "division")},
        ),
    ]
